name = "InfrastructureSickos"
author = "InfrastructureSickos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9ca76231f7c3dee40a6758291989b6c8c6a11d53920687bb12aa1d03710981f"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
