name = "InfrastructureSickos"
author = "InfrastructureSickos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "385002d4f65d55ef9bc1b53cb9c9c3380e37e47cb950abf1a3762f3ff2ef5b4a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
